name: mayur_nile_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.1

  # Service Locator
  get_it: ^7.2.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  dotted_border: ^2.0.0+2
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  visibility_detector: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^1.0.0

  # App Icon
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/icons/social/
    - assets/icons/skills/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
    - family: Victor Mono
      fonts:
        - asset: assets/fonts/VictorMono/VictorMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/VictorMono/VictorMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/VictorMono/VictorMono-Medium.ttf
          weight: 500
